# Generated by Django 4.2.30 on 2026-08-12 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='loan_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='circulation.loan'),
        ),
        migrations.AddField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user_id'], name='idx_loans_user'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='idx_loans_status'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['user_id'], name='idx_fines_user'),
        ),
    ]
